package com.microsoft.schemas.exchange.services._2006.messages;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-09-02T10:13:44.766+02:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", name = "ExchangeServicePortType")
@XmlSeeAlso({com.microsoft.schemas.exchange.services._2006.types.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ExchangeServicePortType {

    @WebMethod(operationName = "DeleteItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/DeleteItem")
    public void deleteItem(
        @WebParam(partName = "request", name = "DeleteItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        DeleteItemType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "DeleteItemResult", mode = WebParam.Mode.OUT, name = "DeleteItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<DeleteItemResponseType> deleteItemResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "ExpandDL", action = "http://schemas.microsoft.com/exchange/services/2006/messages/ExpandDL")
    public void expandDL(
        @WebParam(partName = "request", name = "ExpandDL", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        ExpandDLType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "ExpandDLResult", mode = WebParam.Mode.OUT, name = "ExpandDLResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<ExpandDLResponseType> expandDLResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "SyncFolderHierarchy", action = "http://schemas.microsoft.com/exchange/services/2006/messages/SyncFolderHierarchy")
    public void syncFolderHierarchy(
        @WebParam(partName = "request", name = "SyncFolderHierarchy", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        SyncFolderHierarchyType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "SyncFolderHierarchyResult", mode = WebParam.Mode.OUT, name = "SyncFolderHierarchyResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<SyncFolderHierarchyResponseType> syncFolderHierarchyResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "CreateFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/CreateFolder")
    public void createFolder(
        @WebParam(partName = "request", name = "CreateFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        CreateFolderType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "CreateFolderResult", mode = WebParam.Mode.OUT, name = "CreateFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<CreateFolderResponseType> createFolderResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "GetUserOofSettings", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetUserOofSettings")
    public void getUserOofSettings(
        @WebParam(partName = "GetUserOofSettingsRequest", name = "GetUserOofSettingsRequest", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        GetUserOofSettingsRequest getUserOofSettingsRequest,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types")
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "GetUserOofSettingsResult", mode = WebParam.Mode.OUT, name = "GetUserOofSettingsResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<GetUserOofSettingsResponse> getUserOofSettingsResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "SendItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/SendItem")
    public void sendItem(
        @WebParam(partName = "request", name = "SendItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        SendItemType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "SendItemResult", mode = WebParam.Mode.OUT, name = "SendItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<SendItemResponseType> sendItemResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "AddDelegate", action = "http://schemas.microsoft.com/exchange/services/2006/messages/AddDelegate")
    public void addDelegate(
        @WebParam(partName = "request", name = "AddDelegate", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        AddDelegateType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "AddDelegateResult", mode = WebParam.Mode.OUT, name = "AddDelegateResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<AddDelegateResponseMessageType> addDelegateResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "CreateItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/CreateItem")
    public void createItem(
        @WebParam(partName = "request", name = "CreateItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        CreateItemType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "TimeZoneContext", name = "TimeZoneContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.TimeZoneContextType timeZoneContext,
        @WebParam(partName = "CreateItemResult", mode = WebParam.Mode.OUT, name = "CreateItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<CreateItemResponseType> createItemResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "ConvertId", action = "http://schemas.microsoft.com/exchange/services/2006/messages/ConvertId")
    public void convertId(
        @WebParam(partName = "request", name = "ConvertId", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        ConvertIdType request,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "ConvertIdResult", mode = WebParam.Mode.OUT, name = "ConvertIdResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<ConvertIdResponseType> convertIdResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "RemoveDelegate", action = "http://schemas.microsoft.com/exchange/services/2006/messages/RemoveDelegate")
    public void removeDelegate(
        @WebParam(partName = "request", name = "RemoveDelegate", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        RemoveDelegateType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "RemoveDelegateResult", mode = WebParam.Mode.OUT, name = "RemoveDelegateResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<RemoveDelegateResponseMessageType> removeDelegateResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "UpdateFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/UpdateFolder")
    public void updateFolder(
        @WebParam(partName = "request", name = "UpdateFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        UpdateFolderType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "UpdateFolderResult", mode = WebParam.Mode.OUT, name = "UpdateFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<UpdateFolderResponseType> updateFolderResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "GetEvents", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetEvents")
    public void getEvents(
        @WebParam(partName = "request", name = "GetEvents", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        GetEventsType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "GetEventsResult", mode = WebParam.Mode.OUT, name = "GetEventsResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<GetEventsResponseType> getEventsResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "UpdateDelegate", action = "http://schemas.microsoft.com/exchange/services/2006/messages/UpdateDelegate")
    public void updateDelegate(
        @WebParam(partName = "request", name = "UpdateDelegate", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        UpdateDelegateType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "UpdateDelegateResult", mode = WebParam.Mode.OUT, name = "UpdateDelegateResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<UpdateDelegateResponseMessageType> updateDelegateResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "GetAttachment", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetAttachment")
    public void getAttachment(
        @WebParam(partName = "request", name = "GetAttachment", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        GetAttachmentType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "GetAttachmentResult", mode = WebParam.Mode.OUT, name = "GetAttachmentResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<GetAttachmentResponseType> getAttachmentResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "GetUserAvailability", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetUserAvailability")
    public void getUserAvailability(
        @WebParam(partName = "GetUserAvailabilityRequest", name = "GetUserAvailabilityRequest", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        GetUserAvailabilityRequestType getUserAvailabilityRequest,
        @WebParam(partName = "SerializedSecurityContext", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType serializedSecurityContext,
        @WebParam(partName = "ProxyRequestTypeHeader", name = "ProxyRequestTypeHeader", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.AvailabilityProxyRequestType proxyRequestTypeHeader,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types")
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "GetUserAvailabilityResult", mode = WebParam.Mode.OUT, name = "GetUserAvailabilityResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<GetUserAvailabilityResponseType> getUserAvailabilityResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "DeleteAttachment", action = "http://schemas.microsoft.com/exchange/services/2006/messages/DeleteAttachment")
    public void deleteAttachment(
        @WebParam(partName = "request", name = "DeleteAttachment", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        DeleteAttachmentType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "DeleteAttachmentResult", mode = WebParam.Mode.OUT, name = "DeleteAttachmentResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<DeleteAttachmentResponseType> deleteAttachmentResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "MoveFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/MoveFolder")
    public void moveFolder(
        @WebParam(partName = "request", name = "MoveFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        MoveFolderType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "MoveFolderResult", mode = WebParam.Mode.OUT, name = "MoveFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<MoveFolderResponseType> moveFolderResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "DeleteFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/DeleteFolder")
    public void deleteFolder(
        @WebParam(partName = "request", name = "DeleteFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        DeleteFolderType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "DeleteFolderResult", mode = WebParam.Mode.OUT, name = "DeleteFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<DeleteFolderResponseType> deleteFolderResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "SetUserOofSettings", action = "http://schemas.microsoft.com/exchange/services/2006/messages/SetUserOofSettings")
    public void setUserOofSettings(
        @WebParam(partName = "SetUserOofSettingsRequest", name = "SetUserOofSettingsRequest", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        SetUserOofSettingsRequest setUserOofSettingsRequest,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types")
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "SetUserOofSettingsResult", mode = WebParam.Mode.OUT, name = "SetUserOofSettingsResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<SetUserOofSettingsResponse> setUserOofSettingsResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "CreateAttachment", action = "http://schemas.microsoft.com/exchange/services/2006/messages/CreateAttachment")
    public void createAttachment(
        @WebParam(partName = "request", name = "CreateAttachment", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        CreateAttachmentType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "CreateAttachmentResult", mode = WebParam.Mode.OUT, name = "CreateAttachmentResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<CreateAttachmentResponseType> createAttachmentResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "SyncFolderItems", action = "http://schemas.microsoft.com/exchange/services/2006/messages/SyncFolderItems")
    public void syncFolderItems(
        @WebParam(partName = "request", name = "SyncFolderItems", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        SyncFolderItemsType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "SyncFolderItemsResult", mode = WebParam.Mode.OUT, name = "SyncFolderItemsResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<SyncFolderItemsResponseType> syncFolderItemsResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "GetDelegate", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetDelegate")
    public void getDelegate(
        @WebParam(partName = "request", name = "GetDelegate", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        GetDelegateType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "GetDelegateResult", mode = WebParam.Mode.OUT, name = "GetDelegateResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<GetDelegateResponseMessageType> getDelegateResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "UpdateItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/UpdateItem")
    public void updateItem(
        @WebParam(partName = "request", name = "UpdateItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        UpdateItemType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "TimeZoneContext", name = "TimeZoneContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.TimeZoneContextType timeZoneContext,
        @WebParam(partName = "UpdateItemResult", mode = WebParam.Mode.OUT, name = "UpdateItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<UpdateItemResponseType> updateItemResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "FindItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/FindItem")
    public void findItem(
        @WebParam(partName = "request", name = "FindItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        FindItemType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "FindItemResult", mode = WebParam.Mode.OUT, name = "FindItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<FindItemResponseType> findItemResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "FindFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/FindFolder")
    public void findFolder(
        @WebParam(partName = "request", name = "FindFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        FindFolderType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "FindFolderResult", mode = WebParam.Mode.OUT, name = "FindFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<FindFolderResponseType> findFolderResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "Subscribe", action = "http://schemas.microsoft.com/exchange/services/2006/messages/Subscribe")
    public void subscribe(
        @WebParam(partName = "request", name = "Subscribe", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        SubscribeType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "SubscribeResult", mode = WebParam.Mode.OUT, name = "SubscribeResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<SubscribeResponseType> subscribeResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "CopyFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/CopyFolder")
    public void copyFolder(
        @WebParam(partName = "request", name = "CopyFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        CopyFolderType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "CopyFolderResult", mode = WebParam.Mode.OUT, name = "CopyFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<CopyFolderResponseType> copyFolderResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "ResolveNames", action = "http://schemas.microsoft.com/exchange/services/2006/messages/ResolveNames")
    public void resolveNames(
        @WebParam(partName = "request", name = "ResolveNames", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        ResolveNamesType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "ResolveNamesResult", mode = WebParam.Mode.OUT, name = "ResolveNamesResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<ResolveNamesResponseType> resolveNamesResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "CopyItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/CopyItem")
    public void copyItem(
        @WebParam(partName = "request", name = "CopyItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        CopyItemType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "CopyItemResult", mode = WebParam.Mode.OUT, name = "CopyItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<CopyItemResponseType> copyItemResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "MoveItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/MoveItem")
    public void moveItem(
        @WebParam(partName = "request", name = "MoveItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        MoveItemType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "MoveItemResult", mode = WebParam.Mode.OUT, name = "MoveItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<MoveItemResponseType> moveItemResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "CreateManagedFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/CreateManagedFolder")
    public void createManagedFolder(
        @WebParam(partName = "request", name = "CreateManagedFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        CreateManagedFolderRequestType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "CreateManagedFolderResult", mode = WebParam.Mode.OUT, name = "CreateManagedFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<CreateManagedFolderResponseType> createManagedFolderResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "GetItem", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetItem")
    public void getItem(
        @WebParam(partName = "request", name = "GetItem", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        GetItemType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "GetItemResult", mode = WebParam.Mode.OUT, name = "GetItemResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<GetItemResponseType> getItemResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "Unsubscribe", action = "http://schemas.microsoft.com/exchange/services/2006/messages/Unsubscribe")
    public void unsubscribe(
        @WebParam(partName = "request", name = "Unsubscribe", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        UnsubscribeType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "UnsubscribeResult", mode = WebParam.Mode.OUT, name = "UnsubscribeResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<UnsubscribeResponseType> unsubscribeResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );

    @WebMethod(operationName = "GetFolder", action = "http://schemas.microsoft.com/exchange/services/2006/messages/GetFolder")
    public void getFolder(
        @WebParam(partName = "request", name = "GetFolder", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        GetFolderType request,
        @WebParam(partName = "Impersonation", name = "ExchangeImpersonation", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.ExchangeImpersonationType impersonation,
        @WebParam(partName = "S2SAuth", name = "SerializedSecurityContext", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.SerializedSecurityContextType s2SAuth,
        @WebParam(partName = "MailboxCulture", name = "MailboxCulture", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        java.lang.String mailboxCulture,
        @WebParam(partName = "RequestVersion", name = "RequestServerVersion", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        com.microsoft.schemas.exchange.services._2006.types.RequestServerVersion requestVersion,
        @WebParam(partName = "GetFolderResult", mode = WebParam.Mode.OUT, name = "GetFolderResponse", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages")
        javax.xml.ws.Holder<GetFolderResponseType> getFolderResult,
        @WebParam(partName = "ServerVersion", mode = WebParam.Mode.OUT, name = "ServerVersionInfo", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/types", header = true)
        javax.xml.ws.Holder<com.microsoft.schemas.exchange.services._2006.types.ServerVersionInfo> serverVersion
    );
}
